language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.9.6 USERDEPLOYSERVER="travis" HOST_ADRESS=""
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-slack
# command to run tests
script:
  - python manage.py check

addons:
  ssh_known_hosts: <deploy-host>

before_install:
  openssl aes-256-cbc -K $encrypted_81cbd5b2eb57_key -iv $encrypted_81cbd5b2eb57_iv -in id_rsa.enc -out id_rsa -d

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh $USERDEPLOYSERVER@$HOST_ADRESS 'git pull'
  on:
    branch: master
