language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.9.6
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-slack
# command to run tests
script:
  - python manage.py runserver 0.0.0.0:8000
  
